"""Loader for ORE trade field-mapping data.

ORE_Forge is a separate repo (see docs/FIELDMAP-SOURCE.md) that already
resolves ORE trade fields into concrete XPaths - shared components expanded
inline, multi-instance legs indexed (LegData[1], LegData[2], ...), choice
fields (LegDataType -> Fixed/Floating/...) resolved into their concrete
subtree. That resolution logic (ORE_Forge's UnifiedXPathProvider) is not
reimplemented here - this module only reads it, in place, via ORE_FIELDMAP
(see oregraph.config). ORE_Forge's own JSON files are never vendored,
copied, or flattened into this repo: ORE_Forge stays the source of truth,
and a stale snapshot is refreshed by re-running snapshot(), not by editing
anything here.

This module produces a build-time snapshot only, and emits no graph nodes
or edges. This data has no authority until it has been checked against
fromXML(), which has not happened yet (see docs/FIELDMAP-SOURCE.md Risks).
Nothing here is called from chunks.py, merge.py, or labels.py.
"""
from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import config as configmod


class FieldmapError(RuntimeError):
    pass


@dataclass(frozen=True)
class FieldmapSnapshot:
    """One build-time read of ORE_Forge's resolved trade field mapping."""
    source: Path
    version: dict
    trade_types: list[str]
    nodes_by_trade: dict[str, list[dict[str, Any]]]

    @property
    def total_nodes(self) -> int:
        return sum(len(nodes) for nodes in self.nodes_by_trade.values())


# Keyed by fieldmap root so a process that (unusually) points at more than
# one ORE_Forge checkout doesn't cross-contaminate; UnifiedXPathProvider
# itself caches per-instance already, this just avoids re-importing.
_provider_cache: dict[Path, Any] = {}


def _load_provider(fieldmap_root: Path):
    """Import ORE_Forge's UnifiedXPathProvider by path.

    ORE_Forge is not pip-installable today, and even a proper install
    wouldn't include scripts/xpath/ (it's outside the packaged src/ tree) -
    see docs/FIELDMAP-SOURCE.md Step 1b. ORE_Forge's own tooling
    (scripts/mapping/convert_trades.py, scripts/generate_baselines.py, ...)
    reaches this the same way: insert the repo root on sys.path and import
    as if the checkout were the package root. This is the only route that
    works without modifying ORE_Forge.
    """
    cached = _provider_cache.get(fieldmap_root)
    if cached is not None:
        return cached

    root_str = str(fieldmap_root)
    if root_str not in sys.path:
        sys.path.insert(0, root_str)
    try:
        from scripts.xpath.unified_xpath_provider import UnifiedXPathProvider
    except ImportError as exc:
        raise FieldmapError(
            f"Could not import UnifiedXPathProvider from {fieldmap_root}.\n"
            "Confirm ORE_FIELDMAP points at an ORE_Forge checkout with "
            "scripts/xpath/unified_xpath_provider.py present."
        ) from exc

    provider = UnifiedXPathProvider(data_dir=fieldmap_root / "data" / "unified")
    _provider_cache[fieldmap_root] = provider
    return provider


def snapshot(cfg: configmod.Config) -> FieldmapSnapshot:
    """Read every trade type's resolved XPath nodes from ORE_Forge, in one pass.

    Scoped to domain="trade" - the only domain this loader has been verified
    against (see docs/FIELDMAP-SOURCE.md Steps 2-4). convention/curve_config/
    pricing_engine each have different enumeration semantics in
    UnifiedXPathProvider (e.g. curve configs filter by Is_Top_Level) and
    would need their own verification before being added here.

    Raises FieldmapError if cfg.fieldmap is not set - this is an opt-in
    capability, not a requirement of the core build/merge path.
    """
    if cfg.fieldmap is None:
        raise FieldmapError(
            "No ORE_Forge checkout configured. Set ORE_FIELDMAP to the "
            "ORE_Forge repo root (same pattern as ORE_ENGINE)."
        )
    provider = _load_provider(cfg.fieldmap)
    trade_types = provider.get_trade_types()
    nodes_by_trade = {name: provider.get_xpath("trade", name) for name in trade_types}
    version = configmod.fieldmap_version(cfg.fieldmap)
    return FieldmapSnapshot(
        source=cfg.fieldmap,
        version=version,
        trade_types=trade_types,
        nodes_by_trade=nodes_by_trade,
    )


def save(snap: FieldmapSnapshot, path: Path) -> None:
    """Cache a snapshot as a build intermediate (cfg.fieldmap_out).

    This is a cache of ORE_Forge's *output*, not a vendored copy of its
    source files - it's derived, disposable, and regenerated by re-running
    snapshot(), the same relationship module_out() has to a chunk's source.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "source": str(snap.source),
        "version": snap.version,
        "trade_types": snap.trade_types,
        "nodes_by_trade": snap.nodes_by_trade,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
